name: Build and Publish Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build VSIX
        run: npm run vsce-package

  publish:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Publish to GitHub Packages
        uses: docker://ghcr.io/github/packages-publish-action@v1
        with:
          registry: ghcr.io
          repository: OWNER/REPO/VSIX_PACKAGE_NAME
          token: ${{ secrets.ACTIONS_TOKEN }}
          tag: latest
