name: Build Visual Studio Code package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: NPM Install
        run: npm install --package-lock-only

      - name: Install dependencies
        run: npm install

      - name: Build VSCE package
        run: npm run vsce-package

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Extract version from package.json
        id: extract_version
        run: echo "::set-output name=version::$(node -e "console.log(require('./package.json').version)")"

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: stable
          body: |
            Release notes for version ${{ steps.extract_version.outputs.version }}

            Add your release notes here.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
